### PR TITLE
Exporting Metric Views and Tags

### PR DESCRIPTION
**Pull request by KolbyMcGarrah**
Updates to the observability.go file to be able to register individual views, and update their tags more easily. 

Moved the views to their own exported variables so that they could be registered individually and modified to fit custom needs. Similarly, exported the tags to be able to add or remove tags from the TagKey of different views.

### CODE REVIEW

**Review by odeke-em — APPROVED** [review]
LGTM, thank you @KolbyMcGarrah, and welcome to Orijtech projects!

**Comment by odeke-em** [comment]
@KolbyMcGarrah I’ve also cut a release at https://github.com/orijtech/gomemcache/releases/tag/v0.0.1 so that you can use it easily with go modules. Thank you again for your contribution!

**Comment by KolbyMcGarrah** [comment]
Thanks very much! I appreciate the help!

**Comment by odeke-em** [comment]
Cheers!

**Pull request merged**
